output.. = bin/
bin.includes = META-INF/,\
               .,\
               res/,\
               plugin.properties,\
               plugin.xml,\
               e4model/
javacSource = 21
javacTarget = 21
source.. = src/
