source.. = src/
output.. = bin/
javacSource = 21
javacTarget = 21
bin.includes = META-INF/,\
               .,\
               res/,\
               icons/,\
               images/,\
               plugin.xml,\
               lib/flying-saucer-swt-9.0.7.jar,\
               lib/flying-saucer-core-9.0.7.jar,\
               lib/jtidy-r938.jar
