output.. = bin/
bin.includes = META-INF/,\
               .,\
               res/,\
               plugin.xml,\
               e4model/,\
               plugin.properties,\
               icons/
javacSource = 21
javacTarget = 21
source.. = src/
