output.. = bin/
bin.includes = META-INF/,\
               .,\
               icons/,\
               images/,\
               plugin.properties,\
               plugin.xml,\
               res/,\
               e4model/
javacSource = 21
javacTarget = 21
source.. = src/
