output.. = bin/
bin.includes = .,\
               META-INF/,\
               plugin.properties,\
               plugin.xml,\
               res/,\
               module.xml,\
               module.properties
javacSource = 11
javacTarget = 11
source.. = src
